[2023-03-08T06:07:41.886+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v2.insert_table scheduled__2023-03-07T00:00:00+00:00 [queued]>
[2023-03-08T06:07:41.905+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v2.insert_table scheduled__2023-03-07T00:00:00+00:00 [queued]>
[2023-03-08T06:07:41.906+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T06:07:41.906+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-03-08T06:07:41.906+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T06:07:41.932+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): insert_table> on 2023-03-07 00:00:00+00:00
[2023-03-08T06:07:41.941+0000] {standard_task_runner.py:55} INFO - Started process 10665 to run task
[2023-03-08T06:07:41.948+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgrest_v2', 'insert_table', 'scheduled__2023-03-07T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpqa7tpkr1']
[2023-03-08T06:07:41.950+0000] {standard_task_runner.py:83} INFO - Job 93: Subtask insert_table
[2023-03-08T06:07:42.046+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_postgrest_v2.insert_table scheduled__2023-03-07T00:00:00+00:00 [running]> on host df4d96e1a045
[2023-03-08T06:07:42.097+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'insert_table', field 'sql'. Template: "\n        insert into dag_run (dt,dag_id) values('{{ dt }}','{{dag.dag_id}}')\n        "
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 663, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-03-08T06:07:42.099+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 663, in render_template
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dt' is undefined
[2023-03-08T06:07:42.111+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgrest_v2, task_id=insert_table, execution_date=20230307T000000, start_date=20230308T060741, end_date=20230308T060742
[2023-03-08T06:07:42.126+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 93 for task insert_table ('dt' is undefined; 10665)
[2023-03-08T06:07:42.159+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-08T06:07:42.188+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
