[2023-03-08T05:20:31.815+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v1.create_postgres_table scheduled__2023-03-07T00:00:00+00:00 [queued]>
[2023-03-08T05:20:31.831+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_postgrest_v1.create_postgres_table scheduled__2023-03-07T00:00:00+00:00 [queued]>
[2023-03-08T05:20:31.831+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T05:20:31.831+0000] {taskinstance.py:1280} INFO - Starting attempt 5 of 6
[2023-03-08T05:20:31.832+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-08T05:20:31.861+0000] {taskinstance.py:1300} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-03-07 00:00:00+00:00
[2023-03-08T05:20:31.868+0000] {standard_task_runner.py:55} INFO - Started process 6778 to run task
[2023-03-08T05:20:31.874+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_postgrest_v1', 'create_postgres_table', 'scheduled__2023-03-07T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmpoi3wmnx8']
[2023-03-08T05:20:31.877+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask create_postgres_table
[2023-03-08T05:20:32.018+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_postgrest_v1.create_postgres_table scheduled__2023-03-07T00:00:00+00:00 [running]> on host df4d96e1a045
[2023-03-08T05:20:32.301+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Aditya
AIRFLOW_CTX_DAG_ID=dag_postgrest_v1
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-07T00:00:00+00:00
[2023-03-08T05:20:32.302+0000] {sql.py:254} INFO - Executing: 
        create table if not exist (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
        )
        
[2023-03-08T05:20:32.326+0000] {base.py:73} INFO - Using connection ID 'postgrest_localhost' for task execution.
[2023-03-08T05:20:33.011+0000] {base.py:73} INFO - Using connection ID 'postgrest_localhost' for task execution.
[2023-03-08T05:20:33.014+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-03-08T05:20:33.033+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_postgrest_v1, task_id=create_postgres_table, execution_date=20230307T000000, start_date=20230308T052031, end_date=20230308T052033
[2023-03-08T05:20:33.061+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 79 for task create_postgres_table (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 6778)
[2023-03-08T05:20:33.078+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-08T05:20:33.121+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
